const mdata = {
    posts: [{
        title: "Post 1",
        mainPost: "I read that the flu vaccine provided no protection this season and was actually associated with a higher risk of infection for working-aged adults,.",
        mainURL: "https://www.cochranelibrary.com/cdsr/doi/10.1002/14651858.CD006207.pub6/full",
        supportiveURL: "https://www.medrxiv.org/content/10.1101/2025.01.30.25321421v4",
        supportiveHComment: "This aligns with the report here: ",
        supportiveAIComment: "Supported by this study: ",
        contradictingURL: "https://www.cdc.gov/mmwr/volumes/74/wr/pdfs/mm7406a2-H.pdf",
        contradictingHComment: "This is not correct according to this publication: ",
        contradictingAIComment: "Counter-evidence from this report: ",
        publishDate: "30 January 2023 ",
        mainRURL: "https://t.co/C0XnR8RO3V",
        mainTitle: "Physical interventions to interrupt or reduce the spread of respiratory viruses",
        mainAbs: "Viral epidemics or pandemics of acute respiratory infections (ARIs) pose a global threat. Examples are influenza (H1N1) caused by the H1N1pdm09 virus in 2009, severe acute respiratory syndrome (SARS) in 2003, and coronavirus disease 2019 (COVID‐19) caused by SARS‐CoV‐2 in 2019. Antiviral drugs and vaccines may be insufficient to prevent their spread. This is an update of a Cochrane Review last published in 2020. We include results from studies from the current COVID‐19 pandemic. To assess the effectiveness of physical interventions to interrupt or reduce the spread of acute respiratory viruses. We searched CENTRAL, PubMed, Embase, CINAHL, and two trials registers in October 2022, with backwards and forwards citation analysis on the new studies. We included randomised controlled trials (RCTs) and cluster‐RCTs investigating physical interventions (screening at entry ports, isolation, quarantine, physical distancing, personal protection, hand hygiene, face masks, glasses, and gargling) to prevent respiratory virus transmission. We included 11 new RCTs and cluster‐RCTs (610,872 participants) in this update, bringing the total number of RCTs to 78. Six of the new trials were conducted during the COVID‐19 pandemic; two from Mexico, and one each from Denmark, Bangladesh, England, and Norway. We identified four ongoing studies, of which one is completed, but unreported, evaluating masks concurrent with the COVID‐19 pandemic. Many studies were conducted during non‐epidemic influenza periods. Several were conducted during the 2009 H1N1 influenza pandemic, and others in epidemic influenza seasons up to 2016. Therefore, many studies were conducted in the context of lower respiratory viral circulation and transmission compared to COVID‐19. The included studies were conducted in heterogeneous settings, ranging from suburban schools to hospital wards in high‐income countries; crowded inner city settings in low‐income countries; and an immigrant neighbourhood in a high‐income country. Adherence with interventions was low in many studies. The risk of bias for the RCTs and cluster‐RCTs was mostly high or unclear. We included 12 trials (10 cluster‐RCTs) comparing medical/surgical masks versus no masks to prevent the spread of viral respiratory illness (two trials with healthcare workers and 10 in the community). Wearing masks in the community probably makes little or no difference to the outcome of influenza‐like illness (ILI)/COVID‐19 like illness compared to not wearing masks (risk ratio (RR) 0.95, 95% confidence interval (CI) 0.84 to 1.09; 9 trials, 276,917 participants; moderate‐certainty evidence. Wearing masks in the community probably makes little or no difference to the outcome of laboratory‐confirmed influenza/SARS‐CoV‐2 compared to not wearing masks (RR 1.01, 95% CI 0.72 to 1.42; 6 trials, 13,919 participants; moderate‐certainty evidence). Harms were rarely measured and poorly reported (very low‐certainty evidence). ",
        mainAuthors: "Tom Jefferson, Liz Dooley, Eliana Ferroni, Lubna A Al-Ansary, Mieke L van Driel, Ghada A Bawazeer, Mark A Jones, Tammy C Hoffmann, Justin Clark, Elaine M Beller, Paul P Glasziou, John M Conly",
        mainPublisher: "Cochrane Database of Systematic Reviews ",
        replies: ["reply 1"],
        extSummaryMention: "The Cochrane review evaluates the effectiveness of masks in preventing the spread of respiratory viruses, including COVID-19. The study found little to no evidence that masks significantly reduce transmission in community settings. These findings challenge earlier recommendations and raise questions about the role of masks in managing respiratory virus outbreaks.",
        mentionInPaper: "'Compared with wearing no mask in the community studies only, wearing a mask may make little to no difference in how many people caught a flu-like illness/COVID-like illness (9 studies; 276,917people)' (Page 4)",
        citation: "Jefferson T, Dooley L, Ferroni E, Al-Ansary LA, van Driel ML, Bawazeer GA, Jones MA, Hoffmann TC, Clark J, Beller EM, Glasziou PP, Conly JM. Physical interventions to interrupt or reduce the spread of respiratory viruses. Cochrane Database of Systematic Reviews 2023, Issue 1. Art. No.: CD006207. DOI: 10.1002/14651858.CD006207.pub6. Accessed 28 October 2024.",
        mla_citation : "Jefferson, Tom, et al. Physical interventions to interrupt or reduce the spread of respiratory viruses. Cochrane database of systematic reviews 1 (2023).",
    },
    {
        title: "Post 2",
        mainPost: "An interesting study shows the risk of developing several types of cancer significantly increased one year after vaccination.",
        mainURL: "https://www.mdpi.com/2077-0383/11/8/2219",
        supportiveURL: "https://pubmed.ncbi.nlm.nih.gov/41013858/",
        supportiveHComment: "Exactly, as shown in this paper ",
        supportiveAIComment: "Evidence available in ",
        contradictingURL: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8896046/",
        contradictingHComment: "This paper shows otherwise: ",
        contradictingAIComment: "This is inaccurate—see evidence in ",
        mainRURL: "https://mdpi.com/2077-0383/11/8/2219",
        mainTitle: "The Incidence of Myocarditis and Pericarditis in Post COVID-19 Unvaccinated Patients—A Large Population-Based Study",
        mainAbs: "Background: The first COVID-19 vaccine outside a clinical trial setting was administered on Dec 8, 2020. To ensure global vaccine equity, vaccine targets were set by the COVID-19 Vaccines Global Access (COVAX) Facility and WHO. However, due to vaccine shortfalls, these targets were not achieved by the end of 2021. We aimed to quantify the global impact of the first year of COVID-19 vaccination programmes. Methods: A mathematical model of COVID-19 transmission and vaccination was separately fit to reported COVID-19 mortality and all-cause excess mortality in 185 countries and territories. The impact of COVID-19 vaccination programmes was determined by estimating the additional lives lost if no vaccines had been distributed. We also estimated the additional deaths that would have been averted had the vaccination coverage targets of 20% set by COVAX and 40% set by WHO been achieved by the end of 2021. Findings:  Based on official reported COVID-19 deaths, we estimated that vaccinations prevented 14·4 million (95% credible interval [Crl] 13·7–15·9) deaths from COVID-19 in 185 countries and territories between Dec 8, 2020, and Dec 8, 2021. This estimate rose to 19·8 million (95% Crl 19·1–20·4) deaths from COVID-19 averted when we used excess deaths as an estimate of the true extent of the pandemic, representing a global reduction of 63% in total deaths (19·8 million of 31·4 million) during the first year of COVID-19 vaccination. In COVAX Advance Market Commitment countries, we estimated that 41% of excess mortality (7·4 million [95% Crl 6·8–7·7] of 17·9 million deaths) was averted. In low-income countries, we estimated that an additional 45% (95% CrI 42–49) of deaths could have been averted had the 20% vaccination coverage target set by COVAX been met by each country, and that an additional 111% (105–118) of deaths could have been averted had the 40% target set by WHO been met by each country by the end of 2021. Interpretation: COVID-19 vaccination has substantially altered the course of the pandemic, saving tens of millions of lives globally. However, inadequate access to vaccines in low-income countries has limited the impact in these settings, reinforcing the need for global vaccine equity and coverage.",
        mainAuthors: "Ortal Tuvali, Sagi Tshori, Estela Derazne, Rebecca Regina Hannuna, Arnon Afek, Dan Haberman, Gal Sella and Jacob George",
        mainPublisher: "Lancet Infect Dis ",
        publishDate: "June 23, 2022",
        replies: ["reply 2"],
        extSummaryMention: "The paper by Russell L. Blaylock criticizes global COVID-19 policies, describing them as a 'rolling disaster.' The author, a retired neurosurgeon, argues that the pandemic response was heavily manipulated, driven by bureaucracies, media, and powerful individuals with no medical expertise. Blaylock highlights the suppression of alternative treatments, demonization of dissenting medical professionals, and widespread censorship. He asserts that measures like lockdowns and mask mandates were ineffective, and early treatments could have prevented many deaths. The paper portrays the COVID-19 response as a significant failure, with severe consequences for public trust and medical ethics.",
        mentionInPaper: "'In the current large population study of subjects, who were not vaccinated against SARS-CoV-2, we observed no increase in the incidence of myocarditis or pericarditis from day 10 after positive SARS-CoV-2' (Page 7)",
        citation: "Tuvali O, Tshori S, Derazne E, Hannuna RR, Afek A, Haberman D, Sella G, George J. The Incidence of Myocarditis and Pericarditis in Post COVID-19 Unvaccinated Patients—A Large Population-Based Study. Journal of Clinical Medicine. 2022; 11(8):2219. https://doi.org/10.3390/jcm11082219",
        mla_citation: "Tuvali, Ortal, et al. The incidence of myocarditis and pericarditis in post COVID-19 unvaccinated patients—a large population-based study. Journal of clinical medicine 11.8 (2022): 2219."
    },
    {
        title: "Post 3",
        mainPost: "I found a research saying global warming is primarily caused by natural solar factors, much less sensitive to greenhouse gases than models suggest.",
        mainURL: "https://www.mdpi.com/1467-3045/44/3/73#B39-cimb-44-00073",
        supportiveURL: "https://scienceofclimatechange.org/wp-content/uploads/SCC-Vol5.3-Huijser-Balancing-Act.pdf",
        supportiveHComment: "I know this paper proves it: ",
        supportiveAIComment: "This is supported by findings here: ",
        contradictingURL: "https://www.sciencedirect.com/science/chapter/edited-volume/abs/pii/B9780443190667000126",
        contradictingHComment: "Actually the opposite, per this paper ",
        contradictingAIComment: "Not accurate—see this paper: ",
        mainRURL: " https://tinyurl.com/2s3ujkwh",
        mainTitle: "Intracellular Reverse Transcription of Pfizer BioNTech COVID-19 mRNA Vaccine BNT162b2 In Vitro in Human Liver Cell Line",
        mainAbs: "Preclinical studies of COVID-19 mRNA vaccine BNT162b2, developed by Pfizer and BioNTech, showed reversible hepatic effects in animals that received the BNT162b2 injection. Furthermore, a recent study showed that SARS-CoV-2 RNA can be reverse-transcribed and integrated into the genome of human cells. In this study, we investigated the effect of BNT162b2 on the human liver cell line Huh7 in vitro. Huh7 cells were exposed to BNT162b2, and quantitative PCR was performed on RNA extracted from the cells. We detected high levels of BNT162b2 in Huh7 cells and changes in gene expression of long interspersed nuclear element-1 (LINE-1), which is an endogenous reverse transcriptase. Immunohistochemistry using antibody binding to LINE-1 open reading frame-1 RNA-binding protein (ORFp1) on Huh7 cells treated with BNT162b2 indicated increased nucleus distribution of LINE-1. PCR on genomic DNA of Huh7 cells exposed to BNT162b2 amplified the DNA sequence unique to BNT162b2. Our results indicate a fast up-take of BNT162b2 into human liver cell line Huh7, leading to changes in LINE-1 expression and distribution. We also show that BNT162b2 mRNA is reverse transcribed intracellularly into DNA in as fast as 6 h upon BNT162b2 exposure.",
        mainAuthors: "Markus Aldén, Francisko Olofsson Falla, Daowei Yang, Mohammad Barghouth, Cheng Luan, Magnus Rasmussen and Yang De Marinis",
        mainPublisher: "Current Issues in Molecular Biology",
        publishDate: "25 February 2022",
        replies: ["reply 3"],
        extSummaryMention: "The paper presents a study on the Pfizer-BioNTech COVID-19 mRNA vaccine (BNT162b2) and its effects on human liver cells. It demonstrates that the vaccine mRNA can enter liver cells and be reverse-transcribed into DNA as quickly as six hours after exposure. This challenges earlier claims that the vaccine remains localized at the injection site and does not alter DNA. The study raises concerns about potential gene therapy implications, as the vaccine could influence the genetic material in liver cells",
        mentionInPaper: "'BNT162b2 mRNA is reverse transcribed intracellularly into DNA as fast as 6 h after BNT162b2 exposure; We present evidence on fast entry of BNT162b2 into the cells and subsequent intracellular reverse transcription of BNT162b2 mRNA into DNA.' (Page 8; 9)",
        citation: "Aldén M, Olofsson Falla F, Yang D, Barghouth M, Luan C, Rasmussen M, De Marinis Y. Intracellular Reverse Transcription of Pfizer BioNTech COVID-19 mRNA Vaccine BNT162b2 In Vitro in Human Liver Cell Line. Current Issues in Molecular Biology. 2022; 44(3):1115-1126. https://doi.org/10.3390/cimb44030073",
        mla_citation: "Aldén, Markus, et al. Intracellular reverse transcription of Pfizer BioNTech COVID-19 mRNA vaccine BNT162b2 in vitro in human liver cell line. Current issues in molecular biology 44.3 (2022): 1115-1126."
    },
    {
        title: "Post 4",
        mainPost: "A friend told me there is a research about powering birth rates is not a viable solution to climate change because the impact is too small and takes too long.",
        mainURL: "https://www.mdpi.com/1467-3045/44/3/73#B39-cimb-44-00073",
        supportiveURL: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4535022",
        supportiveHComment: "True, check this evidence paper: ",
        supportiveAIComment: "Evidence available here: ",
        contradictingURL: "https://www.e3s-conferences.org/articles/e3sconf/pdf/2021/60/e3sconf_tpacee2021_11017.pdf",
        contradictingHComment: "That's not accurate—see this study in ",
        contradictingAIComment: "Opposite findings in ",
        mainRURL: " https://tinyurl.com/2s3ujkwh",
        mainTitle: "Intracellular Reverse Transcription of Pfizer BioNTech COVID-19 mRNA Vaccine BNT162b2 In Vitro in Human Liver Cell Line",
        mainAbs: "Preclinical studies of COVID-19 mRNA vaccine BNT162b2, developed by Pfizer and BioNTech, showed reversible hepatic effects in animals that received the BNT162b2 injection. Furthermore, a recent study showed that SARS-CoV-2 RNA can be reverse-transcribed and integrated into the genome of human cells. In this study, we investigated the effect of BNT162b2 on the human liver cell line Huh7 in vitro. Huh7 cells were exposed to BNT162b2, and quantitative PCR was performed on RNA extracted from the cells. We detected high levels of BNT162b2 in Huh7 cells and changes in gene expression of long interspersed nuclear element-1 (LINE-1), which is an endogenous reverse transcriptase. Immunohistochemistry using antibody binding to LINE-1 open reading frame-1 RNA-binding protein (ORFp1) on Huh7 cells treated with BNT162b2 indicated increased nucleus distribution of LINE-1. PCR on genomic DNA of Huh7 cells exposed to BNT162b2 amplified the DNA sequence unique to BNT162b2. Our results indicate a fast up-take of BNT162b2 into human liver cell line Huh7, leading to changes in LINE-1 expression and distribution. We also show that BNT162b2 mRNA is reverse transcribed intracellularly into DNA in as fast as 6 h upon BNT162b2 exposure.",
        mainAuthors: "Markus Aldén, Francisko Olofsson Falla, Daowei Yang, Mohammad Barghouth, Cheng Luan, Magnus Rasmussen and Yang De Marinis",
        mainPublisher: "Current Issues in Molecular Biology",
        publishDate: "25 February 2022",
        replies: ["reply 3"],
        extSummaryMention: "The paper presents a study on the Pfizer-BioNTech COVID-19 mRNA vaccine (BNT162b2) and its effects on human liver cells. It demonstrates that the vaccine mRNA can enter liver cells and be reverse-transcribed into DNA as quickly as six hours after exposure. This challenges earlier claims that the vaccine remains localized at the injection site and does not alter DNA. The study raises concerns about potential gene therapy implications, as the vaccine could influence the genetic material in liver cells",
        mentionInPaper: "'BNT162b2 mRNA is reverse transcribed intracellularly into DNA as fast as 6 h after BNT162b2 exposure; We present evidence on fast entry of BNT162b2 into the cells and subsequent intracellular reverse transcription of BNT162b2 mRNA into DNA.' (Page 8; 9)",
        citation: "Aldén M, Olofsson Falla F, Yang D, Barghouth M, Luan C, Rasmussen M, De Marinis Y. Intracellular Reverse Transcription of Pfizer BioNTech COVID-19 mRNA Vaccine BNT162b2 In Vitro in Human Liver Cell Line. Current Issues in Molecular Biology. 2022; 44(3):1115-1126. https://doi.org/10.3390/cimb44030073",
        mla_citation: "Aldén, Markus, et al. Intracellular reverse transcription of Pfizer BioNTech COVID-19 mRNA vaccine BNT162b2 in vitro in human liver cell line. Current issues in molecular biology 44.3 (2022): 1115-1126."
    },
    {
        title: "Post 5",
        mainPost: "Climate change makes farming more polluting, creating a dangerous cycle that further increases emissions.",
        mainURL: "https://www.mdpi.com/1467-3045/44/3/73#B39-cimb-44-00073",
        supportiveURL: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4535022",
        supportiveHComment: "True, check this evidence paper: ",
        supportiveAIComment: "Evidence available here: ",
        contradictingURL: "https://www.e3s-conferences.org/articles/e3sconf/pdf/2021/60/e3sconf_tpacee2021_11017.pdf",
        contradictingHComment: "That's not accurate—see this study in ",
        contradictingAIComment: "Opposite findings in ",
        mainRURL: " https://tinyurl.com/2s3ujkwh",
        mainTitle: "Intracellular Reverse Transcription of Pfizer BioNTech COVID-19 mRNA Vaccine BNT162b2 In Vitro in Human Liver Cell Line",
        mainAbs: "Preclinical studies of COVID-19 mRNA vaccine BNT162b2, developed by Pfizer and BioNTech, showed reversible hepatic effects in animals that received the BNT162b2 injection. Furthermore, a recent study showed that SARS-CoV-2 RNA can be reverse-transcribed and integrated into the genome of human cells. In this study, we investigated the effect of BNT162b2 on the human liver cell line Huh7 in vitro. Huh7 cells were exposed to BNT162b2, and quantitative PCR was performed on RNA extracted from the cells. We detected high levels of BNT162b2 in Huh7 cells and changes in gene expression of long interspersed nuclear element-1 (LINE-1), which is an endogenous reverse transcriptase. Immunohistochemistry using antibody binding to LINE-1 open reading frame-1 RNA-binding protein (ORFp1) on Huh7 cells treated with BNT162b2 indicated increased nucleus distribution of LINE-1. PCR on genomic DNA of Huh7 cells exposed to BNT162b2 amplified the DNA sequence unique to BNT162b2. Our results indicate a fast up-take of BNT162b2 into human liver cell line Huh7, leading to changes in LINE-1 expression and distribution. We also show that BNT162b2 mRNA is reverse transcribed intracellularly into DNA in as fast as 6 h upon BNT162b2 exposure.",
        mainAuthors: "Markus Aldén, Francisko Olofsson Falla, Daowei Yang, Mohammad Barghouth, Cheng Luan, Magnus Rasmussen and Yang De Marinis",
        mainPublisher: "Current Issues in Molecular Biology",
        publishDate: "25 February 2022",
        replies: ["reply 3"],
        extSummaryMention: "The paper presents a study on the Pfizer-BioNTech COVID-19 mRNA vaccine (BNT162b2) and its effects on human liver cells. It demonstrates that the vaccine mRNA can enter liver cells and be reverse-transcribed into DNA as quickly as six hours after exposure. This challenges earlier claims that the vaccine remains localized at the injection site and does not alter DNA. The study raises concerns about potential gene therapy implications, as the vaccine could influence the genetic material in liver cells",
        mentionInPaper: "'BNT162b2 mRNA is reverse transcribed intracellularly into DNA as fast as 6 h after BNT162b2 exposure; We present evidence on fast entry of BNT162b2 into the cells and subsequent intracellular reverse transcription of BNT162b2 mRNA into DNA.' (Page 8; 9)",
        citation: "Aldén M, Olofsson Falla F, Yang D, Barghouth M, Luan C, Rasmussen M, De Marinis Y. Intracellular Reverse Transcription of Pfizer BioNTech COVID-19 mRNA Vaccine BNT162b2 In Vitro in Human Liver Cell Line. Current Issues in Molecular Biology. 2022; 44(3):1115-1126. https://doi.org/10.3390/cimb44030073",
        mla_citation: "Aldén, Markus, et al. Intracellular reverse transcription of Pfizer BioNTech COVID-19 mRNA vaccine BNT162b2 in vitro in human liver cell line. Current issues in molecular biology 44.3 (2022): 1115-1126."
    },
    {
        title: "Post 6",
        mainPost: "Climate change threatens to trigger a rapid acceleration in species extinction worldwide.",
        mainURL: "https://www.mdpi.com/1467-3045/44/3/73#B39-cimb-44-00073",
        supportiveURL: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4535022",
        supportiveHComment: "True, check this evidence paper: ",
        supportiveAIComment: "Evidence available here: ",
        contradictingURL: "https://www.e3s-conferences.org/articles/e3sconf/pdf/2021/60/e3sconf_tpacee2021_11017.pdf",
        contradictingHComment: "That's not accurate—see this study in ",
        contradictingAIComment: "Opposite findings in ",
        mainRURL: " https://tinyurl.com/2s3ujkwh",
        mainTitle: "Intracellular Reverse Transcription of Pfizer BioNTech COVID-19 mRNA Vaccine BNT162b2 In Vitro in Human Liver Cell Line",
        mainAbs: "Preclinical studies of COVID-19 mRNA vaccine BNT162b2, developed by Pfizer and BioNTech, showed reversible hepatic effects in animals that received the BNT162b2 injection. Furthermore, a recent study showed that SARS-CoV-2 RNA can be reverse-transcribed and integrated into the genome of human cells. In this study, we investigated the effect of BNT162b2 on the human liver cell line Huh7 in vitro. Huh7 cells were exposed to BNT162b2, and quantitative PCR was performed on RNA extracted from the cells. We detected high levels of BNT162b2 in Huh7 cells and changes in gene expression of long interspersed nuclear element-1 (LINE-1), which is an endogenous reverse transcriptase. Immunohistochemistry using antibody binding to LINE-1 open reading frame-1 RNA-binding protein (ORFp1) on Huh7 cells treated with BNT162b2 indicated increased nucleus distribution of LINE-1. PCR on genomic DNA of Huh7 cells exposed to BNT162b2 amplified the DNA sequence unique to BNT162b2. Our results indicate a fast up-take of BNT162b2 into human liver cell line Huh7, leading to changes in LINE-1 expression and distribution. We also show that BNT162b2 mRNA is reverse transcribed intracellularly into DNA in as fast as 6 h upon BNT162b2 exposure.",
        mainAuthors: "Markus Aldén, Francisko Olofsson Falla, Daowei Yang, Mohammad Barghouth, Cheng Luan, Magnus Rasmussen and Yang De Marinis",
        mainPublisher: "Current Issues in Molecular Biology",
        publishDate: "25 February 2022",
        replies: ["reply 3"],
        extSummaryMention: "The paper presents a study on the Pfizer-BioNTech COVID-19 mRNA vaccine (BNT162b2) and its effects on human liver cells. It demonstrates that the vaccine mRNA can enter liver cells and be reverse-transcribed into DNA as quickly as six hours after exposure. This challenges earlier claims that the vaccine remains localized at the injection site and does not alter DNA. The study raises concerns about potential gene therapy implications, as the vaccine could influence the genetic material in liver cells",
        mentionInPaper: "'BNT162b2 mRNA is reverse transcribed intracellularly into DNA as fast as 6 h after BNT162b2 exposure; We present evidence on fast entry of BNT162b2 into the cells and subsequent intracellular reverse transcription of BNT162b2 mRNA into DNA.' (Page 8; 9)",
        citation: "Aldén M, Olofsson Falla F, Yang D, Barghouth M, Luan C, Rasmussen M, De Marinis Y. Intracellular Reverse Transcription of Pfizer BioNTech COVID-19 mRNA Vaccine BNT162b2 In Vitro in Human Liver Cell Line. Current Issues in Molecular Biology. 2022; 44(3):1115-1126. https://doi.org/10.3390/cimb44030073",
        mla_citation: "Aldén, Markus, et al. Intracellular reverse transcription of Pfizer BioNTech COVID-19 mRNA vaccine BNT162b2 in vitro in human liver cell line. Current issues in molecular biology 44.3 (2022): 1115-1126."
    },
    {
        title: "Post 7",
        mainPost: "For over two centuries, vaccines have been our most effective tool for saving lives and wiping out deadly diseases.",
        mainURL: "https://www.mdpi.com/1467-3045/44/3/73#B39-cimb-44-00073",
        supportiveURL: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4535022",
        supportiveHComment: "True, check this evidence paper: ",
        supportiveAIComment: "Evidence available here: ",
        contradictingURL: "https://www.e3s-conferences.org/articles/e3sconf/pdf/2021/60/e3sconf_tpacee2021_11017.pdf",
        contradictingHComment: "That's not accurate—see this study in ",
        contradictingAIComment: "Opposite findings in ",
        mainRURL: " https://tinyurl.com/2s3ujkwh",
        mainTitle: "Intracellular Reverse Transcription of Pfizer BioNTech COVID-19 mRNA Vaccine BNT162b2 In Vitro in Human Liver Cell Line",
        mainAbs: "Preclinical studies of COVID-19 mRNA vaccine BNT162b2, developed by Pfizer and BioNTech, showed reversible hepatic effects in animals that received the BNT162b2 injection. Furthermore, a recent study showed that SARS-CoV-2 RNA can be reverse-transcribed and integrated into the genome of human cells. In this study, we investigated the effect of BNT162b2 on the human liver cell line Huh7 in vitro. Huh7 cells were exposed to BNT162b2, and quantitative PCR was performed on RNA extracted from the cells. We detected high levels of BNT162b2 in Huh7 cells and changes in gene expression of long interspersed nuclear element-1 (LINE-1), which is an endogenous reverse transcriptase. Immunohistochemistry using antibody binding to LINE-1 open reading frame-1 RNA-binding protein (ORFp1) on Huh7 cells treated with BNT162b2 indicated increased nucleus distribution of LINE-1. PCR on genomic DNA of Huh7 cells exposed to BNT162b2 amplified the DNA sequence unique to BNT162b2. Our results indicate a fast up-take of BNT162b2 into human liver cell line Huh7, leading to changes in LINE-1 expression and distribution. We also show that BNT162b2 mRNA is reverse transcribed intracellularly into DNA in as fast as 6 h upon BNT162b2 exposure.",
        mainAuthors: "Markus Aldén, Francisko Olofsson Falla, Daowei Yang, Mohammad Barghouth, Cheng Luan, Magnus Rasmussen and Yang De Marinis",
        mainPublisher: "Current Issues in Molecular Biology",
        publishDate: "25 February 2022",
        replies: ["reply 3"],
        extSummaryMention: "The paper presents a study on the Pfizer-BioNTech COVID-19 mRNA vaccine (BNT162b2) and its effects on human liver cells. It demonstrates that the vaccine mRNA can enter liver cells and be reverse-transcribed into DNA as quickly as six hours after exposure. This challenges earlier claims that the vaccine remains localized at the injection site and does not alter DNA. The study raises concerns about potential gene therapy implications, as the vaccine could influence the genetic material in liver cells",
        mentionInPaper: "'BNT162b2 mRNA is reverse transcribed intracellularly into DNA as fast as 6 h after BNT162b2 exposure; We present evidence on fast entry of BNT162b2 into the cells and subsequent intracellular reverse transcription of BNT162b2 mRNA into DNA.' (Page 8; 9)",
        citation: "Aldén M, Olofsson Falla F, Yang D, Barghouth M, Luan C, Rasmussen M, De Marinis Y. Intracellular Reverse Transcription of Pfizer BioNTech COVID-19 mRNA Vaccine BNT162b2 In Vitro in Human Liver Cell Line. Current Issues in Molecular Biology. 2022; 44(3):1115-1126. https://doi.org/10.3390/cimb44030073",
        mla_citation: "Aldén, Markus, et al. Intracellular reverse transcription of Pfizer BioNTech COVID-19 mRNA vaccine BNT162b2 in vitro in human liver cell line. Current issues in molecular biology 44.3 (2022): 1115-1126."
    },
    {
        title: "Post 8",
        mainPost: "There is no increased risk of autism, asthma, or autoimmune diseases in vaccinated children.",
        mainURL: "https://www.mdpi.com/1467-3045/44/3/73#B39-cimb-44-00073",
        supportiveURL: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4535022",
        supportiveHComment: "True, check this evidence paper: ",
        supportiveAIComment: "Evidence available here: ",
        contradictingURL: "https://www.e3s-conferences.org/articles/e3sconf/pdf/2021/60/e3sconf_tpacee2021_11017.pdf",
        contradictingHComment: "That's not accurate—see this study in ",
        contradictingAIComment: "Opposite findings in ",
        mainRURL: " https://tinyurl.com/2s3ujkwh",
        mainTitle: "Intracellular Reverse Transcription of Pfizer BioNTech COVID-19 mRNA Vaccine BNT162b2 In Vitro in Human Liver Cell Line",
        mainAbs: "Preclinical studies of COVID-19 mRNA vaccine BNT162b2, developed by Pfizer and BioNTech, showed reversible hepatic effects in animals that received the BNT162b2 injection. Furthermore, a recent study showed that SARS-CoV-2 RNA can be reverse-transcribed and integrated into the genome of human cells. In this study, we investigated the effect of BNT162b2 on the human liver cell line Huh7 in vitro. Huh7 cells were exposed to BNT162b2, and quantitative PCR was performed on RNA extracted from the cells. We detected high levels of BNT162b2 in Huh7 cells and changes in gene expression of long interspersed nuclear element-1 (LINE-1), which is an endogenous reverse transcriptase. Immunohistochemistry using antibody binding to LINE-1 open reading frame-1 RNA-binding protein (ORFp1) on Huh7 cells treated with BNT162b2 indicated increased nucleus distribution of LINE-1. PCR on genomic DNA of Huh7 cells exposed to BNT162b2 amplified the DNA sequence unique to BNT162b2. Our results indicate a fast up-take of BNT162b2 into human liver cell line Huh7, leading to changes in LINE-1 expression and distribution. We also show that BNT162b2 mRNA is reverse transcribed intracellularly into DNA in as fast as 6 h upon BNT162b2 exposure.",
        mainAuthors: "Markus Aldén, Francisko Olofsson Falla, Daowei Yang, Mohammad Barghouth, Cheng Luan, Magnus Rasmussen and Yang De Marinis",
        mainPublisher: "Current Issues in Molecular Biology",
        publishDate: "25 February 2022",
        replies: ["reply 3"],
        extSummaryMention: "The paper presents a study on the Pfizer-BioNTech COVID-19 mRNA vaccine (BNT162b2) and its effects on human liver cells. It demonstrates that the vaccine mRNA can enter liver cells and be reverse-transcribed into DNA as quickly as six hours after exposure. This challenges earlier claims that the vaccine remains localized at the injection site and does not alter DNA. The study raises concerns about potential gene therapy implications, as the vaccine could influence the genetic material in liver cells",
        mentionInPaper: "'BNT162b2 mRNA is reverse transcribed intracellularly into DNA as fast as 6 h after BNT162b2 exposure; We present evidence on fast entry of BNT162b2 into the cells and subsequent intracellular reverse transcription of BNT162b2 mRNA into DNA.' (Page 8; 9)",
        citation: "Aldén M, Olofsson Falla F, Yang D, Barghouth M, Luan C, Rasmussen M, De Marinis Y. Intracellular Reverse Transcription of Pfizer BioNTech COVID-19 mRNA Vaccine BNT162b2 In Vitro in Human Liver Cell Line. Current Issues in Molecular Biology. 2022; 44(3):1115-1126. https://doi.org/10.3390/cimb44030073",
        mla_citation: "Aldén, Markus, et al. Intracellular reverse transcription of Pfizer BioNTech COVID-19 mRNA vaccine BNT162b2 in vitro in human liver cell line. Current issues in molecular biology 44.3 (2022): 1115-1126."
    }]
};

export { mdata };